### ISSUE TITLE
pip3 won't install pyengine with exit status 1

### ISSUE THREAD

**Issue by szb512** [pyengine-2d/PyEngine#1]
Log:
C:\Windows\system32>pip3 install pyengine
Collecting pyengine
  Using cached pyengine-0.0.4.tar.gz (3.4 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files (x86)\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\blued\\AppData\\Local\\Temp\\pip-install-j1ozxjaf\\pyengine\\setup.py'"'"'; __file__='"'"'C:\\Users\\blued\\AppData\\Local\\Temp\\pip-install-j1ozxjaf\\pyengine\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\blued\AppData\Local\Temp\pip-install-j1ozxjaf\pyengine\pip-egg-info'
         cwd: C:\Users\blued\AppData\Local\Temp\pip-install-j1ozxjaf\pyengine\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\blued\AppData\Local\Temp\pip-install-j1ozxjaf\pyengine\setup.py", line 3, in <module>
        with open('./pyengine/ReadMe.md','r',encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: './pyengine/ReadMe.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I ran this in command prompt as an admin:
pip3 install pyengine
and it gives me in python FileNotFoundError with exit status 1

**Comment by AlexisHuvier** [comment]
If you want install PyEngine with pip, you must write 'pip3 install PyEngine-2d'.

**Comment by szb512** [comment]
Ok then...
